-- stg_posts: Cleaned posts with source metadata, normalized dates, and generated slugs.
-- Sources: raw_blog_posts JOIN raw_blog_sources
-- Note: post_slug is a preview/convenience slug for querying. The canonical slug for
-- vault file naming is generated by src/vault/note_generator.py (Story 3.2) which adds
-- hash suffixes for collision handling. Do not use post_slug as a file path identifier.

with cleaned_posts as (
    select
        p.id,
        p.source_id,
        s.name as source_name,
        s.category,
        trim(p.title) as title,
        trim(p.body) as body,
        p.url,
        coalesce(nullif(trim(p.author_name), ''), 'Unknown') as author_name,
        p.publication_date::date as publication_date,
        trim(both '-' from lower(regexp_replace(left(trim(p.title), 80), '[^a-zA-Z0-9]+', '-', 'g'))) as post_slug,
        p.created_at
    from {{ source('raw', 'raw_blog_posts') }} as p
    left join {{ source('raw', 'raw_blog_sources') }} as s
        on p.source_id = s.id
)

select * from cleaned_posts
